source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'Navigato_Example' do
  pod 'Navigato', :path => '../'

  target 'Navigato_Tests' do
    inherit! :search_paths
  end
end
